filters =\
  grayscale,\
  gammacorrection


filter.grayscale.class=ICGFilter.filters.GrayscaleFilter
filter.grayscale.icon=/icons/grayscale.png
filter.grayscale.name=Grayscale
filter.grayscale.description=Черно-белый фильтр

filter.gammacorrection.class=ICGFilter.filters.GammaCorrectionFilter
filter.gammacorrection.icon=/icons/gamma_correction.png
filter.gammacorrection.name=GammaCorrection
filter.gammacorrection.description=Гамма-коррекция