filters =\
  grayscale,\
  gamma_correction


filter.grayscale.class=ICGFilter.filters.GrayscaleFilter
filter.grayscale.icon=/icons/grayscale.png
filter.grayscale.name=Grayscale
filter.grayscale.description=Черно-белый фильтр

filter.gamma_correction.class=ICGFilter.filters.GammaCorrectionFilter
filter.gamma_correction.icon=/icons/gamma_correction.png
filter.gamma_correction.name=GammaCorrection
filter.gamma_correction.description=Гамма-коррекция